//
//  File.swift
//  
//
//  Created by Morten Just on 2/19/22.
//

import Foundation

public enum HighlighterTheme: String {
  case a11yDark = "a11y-dark"
  case a11yLight = "a11y-light"
  case agate = "agate"
  case anOldHope = "an-old-hope"
  case androidStudio = "androidstudio"
  case arduinoLight = "arduino-light"
  case arta = "arta"
  case ascetic = "ascetic"
  case atelierCaveDark = "atelier-cave-dark"
  case atelierCaveLight = "atelier-cave-light"
  case atelierDuneDark = "atelier-dune-dark"
  case atelierDuneLight = "atelier-dune-light"
  case atelierEstuaryDark = "atelier-estuary-dark"
  case atelierEstuaryLight = "atelier-estuary-light"
  case atelierForestDark = "atelier-forest-dark"
  case atelierForestLight = "atelier-forest-light"
  case atelierHeathDark = "atelier-heath-dark"
  case atelierHeathLight = "atelier-heath-light"
  case atelierLakesideDark = "atelier-lakeside-dark"
  case atelierLakesideLight = "atelier-lakeside-light"
  case atelierPlateauDark = "atelier-plateau-dark"
  case atelierPlateauLight = "atelier-plateau-light"
  case atelierSavannaDark = "atelier-savanna-dark"
  case atelierSavannaLight = "atelier-savanna-light"
  case atelierSeasideDark = "atelier-seaside-dark"
  case atelierSeasideLight = "atelier-seaside-light"
  case atelierSulphurpoolDark = "atelier-sulphurpool-dark"
  case atelierSulphurpoolLight = "atelier-sulphurpool-light"
  case atomOneDarkReasonable = "atom-one-dark-reasonable"
  case atomOneDark = "atom-one-dark"
  case atomOneLight = "atom-one-light"
  case brownPaper = "brown-paper"
  case codepenEmbed = "codepen-embed"
  case colorBrewer = "color-brewer"
  case darcula = "darcula"
  case dark = "dark"
  case darkula = "darkula"
  case `default` = "default"
  case docco = "docco"
  case dracula = "dracula"
  case far = "far"
  case foundation = "foundation"
  case githubGist = "github-gist"
  case github = "github"
  case gml = "gml"
  case googlecode = "googlecode"
  case grayscale = "grayscale"
  case gruvboxDark = "gruvbox-dark"
  case gruvboxLight = "gruvbox-light"
  case hopscotch = "hopscotch"
  case hybrid = "hybrid"
  case idea = "idea"
  case irBlack = "ir-black"
  case isblEditorDark = "isbl-editor-dark"
  case isblEditorLight = "isbl-editor-light"
  case kimbieDark = "kimbie.dark"
  case kimbieLight = "kimbie.light"
  case lightfair = "lightfair"
  case magula = "magula"
  case monoBlue = "mono-blue"
  case monokaiSublime = "monokai-sublime"
  case monokai = "monokai"
  case nord = "nord"
  case obsidian = "obsidian"
  case ocean = "ocean"
  case paraisoDark = "paraiso-dark"
  case paraisoLight = "paraiso-light"
  case pojoaque = "pojoaque"
  case purebasic = "purebasic"
  case qtcreatorDark = "qtcreator_dark"
  case qtcreatorLight = "qtcreator_light"
  case railscasts = "railscasts"
  case rainbow = "rainbow"
  case routeros = "routeros"
  case schoolBook = "school-book"
  case shadesOfPurple = "shades-of-purple"
  case solarizedDark = "solarized-dark"
  case solarizedLight = "solarized-light"
  case sunburst = "sunburst"
  case tomorrowNightBlue = "tomorrow-night-blue"
  case tomorrowNightBright = "tomorrow-night-bright"
  case tomorrowNightEighties = "tomorrow-night-eighties"
  case tomorrowNight = "tomorrow-night"
  case tomorrow = "tomorrow"
  case vs = "vs"
  case vs2015 = "vs2015"
  case xcode = "xcode"
  case xcodeDark = "xcode-dark"
  case xt256 = "xt256"
  case zenburn = "zenburn"
}
